# Generated by Django 3.2.8 on 2022-02-15 05:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('liffapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cpu',
            name='vendor',
        ),
    ]
