# Generated by Django 3.2.8 on 2022-02-15 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('liffapp', '0002_remove_cpu_vendor'),
    ]

    operations = [
        migrations.AddField(
            model_name='cpu',
            name='vendor',
            field=models.CharField(default='', max_length=100),
        ),
    ]
